# Names of nodes to start
#   most will only start one node:
CELERYD_NODES="clawer-celeryd-worker"


# Absolute or relative path to the 'celery' command:
#CELERY_BIN="/home/virtualenvs/py27/bin/celery"
CELERYD_MULTI="/home/virtualenvs/py27/bin/celery multi"

# App instance to use
# comment out this line if you don't use an app
CELERY_APP="clawer"
# or fully qualified:
#CELERY_APP="proj.tasks:app"

# Where to chdir at start.
CELERYD_CHDIR="/home/webapps/nice-clawer/clawer"

# Extra command-line arguments to the worker
CELERYD_OPTS="--time-limit=1800 --concurrency=1"

# %N will be replaced with the first part of the nodename.
CELERYD_LOG_FILE="/home/web_log/clawer-celery/%N.log"
CELERYD_PID_FILE="/var/run/clawer-celery/%N.pid"

# Workers should run as an unprivileged user.
#   You need to create this user manually (or you can choose
#   a user/group combination that already exists, e.g. nobody).
CELERYD_USER="celery"
CELERYD_GROUP="celery"

# If enabled pid and log directories will be created if missing,
# and owned by the userid/group configured.
CELERY_CREATE_DIRS=1
