# -*- coding: utf-8 -*-

json_paths = (
    "profiles/jsons/guangxi.json",
    "profiles/jsons/yunnan.json",
    "profiles/jsons/beijing.json",
    "profiles/jsons/hebei.json",
    "profiles/jsons/henan.json",
    "profiles/jsons/heilongjiang.json",
    "profiles/jsons/tianjin.json",
    "profiles/jsons/zhejiang.json",
    "profiles/jsons/neimeng.json",
)
"profiles/jsons/guangxi.json",
"profiles/jsons/yunnan.json",
"profiles/jsons/beijing.json",
"profiles/jsons/hebei.json",
"profiles/jsons/henan.json",
"profiles/jsons/heilongjiang.json",
"profiles/jsons/tianjin.json",
"profiles/jsons/zhejiang.json",
"profiles/jsons/neimeng.json",

"profiles/jsons/anhui.json",
"profiles/jsons/fujian.json",
"profiles/jsons/guangdong.json",
"profiles/jsons/hunan.json",
"profiles/jsons/jiangsu.json",
"profiles/jsons/shandong.json",
"profiles/jsons/shanghai.json",
"profiles/jsons/sichuan.json",
"profiles/jsons/zongju.json",
"profiles/jsons/gansu.json",

"profiles/jsons/liaoning.json",
"profiles/jsons/shaanxi.json",
